export const AUTH = { 
    AUTHENTICATION_START: "AUTHENTICATION_START",
    AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
    AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
    LOG_OUT_START: "LOG_OUT_START",
    LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
    LOG_OUT_ERROR: "LOG_OUT_ERROR"
};