export const PRODUCT_GROUPS_ACTIONS = {
    GET_GROUPS_START: "GET_GROUPS",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_ERROR: "GET_GROUPS_ERROR",
    CREATE_GROUP_START: "CREATE_GROUP_START",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_ERROR: "CREATE_GROUP_ERROR",
    UPDATE_GROUP_START: "UPDATE_GROUP_START",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
    UPDATE_GROUP_ERROR: "UPDATE_GROUP_ERROR",
    DELETE_GROUP_START: "DELETE_GROUP_START",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_ERROR: "DELETE_GROUP_ERROR",
}